# Generated by Django 3.2.15 on 2022-09-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_clubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='takim_logo',
            field=models.ImageField(blank=True, default='takim_resim/mnc.png', null=True, upload_to='takim_resim/', verbose_name='Takım Resmi Ekle'),
        ),
    ]
