# Generated by Django 3.2.15 on 2022-09-29 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_clubs_takim_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='clup_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.BigIntegerField()),
                ('win', models.BigIntegerField()),
                ('loss', models.BigIntegerField()),
                ('takim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.clubs')),
            ],
        ),
    ]
