# Generated by Django 3.2.15 on 2022-09-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_clup_point'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clup_point',
            new_name='club_point',
        ),
    ]
