# Generated by Django 3.2.15 on 2022-09-28 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_clup_point_club_point'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='club_point',
            new_name='clup_point',
        ),
    ]
